spring:
  application:
    name: authproject
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  user:
    name: testadmin
    password: testadmin
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG

